name: Periodic Model Calibration

on: 
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Ensure directories exist
      run: |
        mkdir -p $GITHUB_WORKSPACE/models
        mkdir -p $GITHUB_WORKSPACE/metrics

    - name: Generate Timestamp
      id: timestamp
      run: echo "timestamp=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

    - name: Set File Permissions
      run: chmod +x ./src/train_model.py ./src/evaluate_model.py

    - name: Retrain Model
      run: |
        python ./src/train_model.py --timestamp "${{ steps.timestamp.outputs.timestamp }}"

    - name: Evaluate Model and Log Metrics
      run: |
        python ./src/evaluate_model.py --timestamp "${{ steps.timestamp.outputs.timestamp }}" --base_dir "$GITHUB_WORKSPACE"

    - name: Commit and Push Changes
      run: |
        timestamp="${{ steps.timestamp.outputs.timestamp }}"
        model_filename="model_${timestamp}_rf_model.joblib"
        metrics_filename="${timestamp}_metrics.json"

        git config --global user.email "26876927+raminmohammadi@users.noreply.github.com"
        git config --global user.name "raminmohammadi"

        git add $GITHUB_WORKSPACE/models/$model_filename $GITHUB_WORKSPACE/metrics/$metrics_filename
        git commit -m "Add metrics and updated model for timestamp $timestamp"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}