name: Lab1 - Pytest

on:
  push:
    branches: ["main"]
    paths:
      - "Labs/Github_Labs/Lab1/**"
  pull_request:
    branches: ["main"]
    paths:
      - "Labs/Github_Labs/Lab1/**"

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
      # ensure python can import src package
      PYTHONPATH: Labs/Github_Labs/Lab1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          if [ -f Labs/Github_Labs/Lab1/requirements.txt ]; then pip install -r Labs/Github_Labs/Lab1/requirements.txt; fi

      - name: Run pytest (Lab1)
        working-directory: Labs/Github_Labs/Lab1
        run: |
          pytest test -q --maxfail=1 --showlocals --junitxml=pytest-report.xml

      - name: Upload pytest report
        uses: actions/upload-artifact@v3
        with:
          name: lab1-pytest-report
          path: Labs/Github_Labs/Lab1/pytest-report.xml
