name: Testing with Pytest
run-name: Pytest

on:
  push:
    branches:
      - main
      - "releases/**"
    branches-ignore:
      - dev

  label:
    types:
      - created
  issues:
    types:
      - opened
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # ensure tests can import src package
      PYTHONPATH: Labs/Github_Labs/Lab1
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f Labs/Github_Labs/Lab1/requirements.txt ]; then
            pip install -r Labs/Github_Labs/Lab1/requirements.txt
          fi

      - name: Run tests and generate XML report
        working-directory: Labs/Github_Labs/Lab1
        run: |
          pytest test -q --junitxml=pytest-report.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: Labs/Github_Labs/Lab1/pytest-report.xml

      - name: Notify on success
        if: success()
        run: echo "Tests passed successfully"

      - name: Notify on failure
        if: failure()
        run: echo "Tests failed"
