name: Python Unittests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: Labs/Github_Labs/Lab1
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f Labs/Github_Labs/Lab1/requirements.txt ]; then
            pip install -r Labs/Github_Labs/Lab1/requirements.txt
          fi

      - name: Run unittests
        working-directory: Labs/Github_Labs/Lab1
        run: python -m unittest test.test_area_calculator_unittest -v

      - name: Notify on success
        if: success()
        run: echo "Unit tests passed successfully"

      - name: Notify on failure
        if: failure()
        run: echo "Unit tests failed"
