name: Lab1 - Unittest

on:
  push:
    branches: ["main"]
    paths:
      - "Labs/Github_Labs/Lab1/**"
  pull_request:
    branches: ["main"]
    paths:
      - "Labs/Github_Labs/Lab1/**"

jobs:
  unittest:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: Labs/Github_Labs/Lab1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          if [ -f Labs/Github_Labs/Lab1/requirements.txt ]; then pip install -r Labs/Github_Labs/Lab1/requirements.txt; fi

      - name: Run unittests (Lab1)
        working-directory: Labs/Github_Labs/Lab1
        run: |
          python -m unittest discover -v -s test
